spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Utkarsh Bank accounts related to Prod APIs"
  contactDetails:
    name: "Rishabh Singh - Product Owner"
    email: "{cypher}188aca6144c64af6bb5dccbadc2c0b689a264f6cf2e485a9650d74bf521e6d7e61e39dc028d68fd3bd93a62b0e72bebf"
  onCallSupport:
    - (055)231-2312
    - (555)233-2233
